---
# defaults file for zookeeper

zoo_install_dir: /users/dporte7/
zoo_conf_dir: /users/dporte7/apache-zookeeper-3.5.5/conf
zoo_root_dir: /users/dporte7/apache-zookeeper-3.5.5
zoo_bin_dir: /users/dporte7/apache-zookeeper-3.5.5/bin
zoo3-5_link: https://archive.apache.org/dist/zookeeper/zookeeper-3.5.5/apache-zookeeper-3.5.5.tar.gz
zoo3-4_link: https://archive.apache.org/dist/zookeeper/zookeeper-3.4.13/zookeeper-3.4.13.tar.gz
