---
# defaults file for solr

# VARIABLE PRECEDENCE
# If multiple variables of the same name are defined in different places, they win in a certain order, which is:
# extra vars (-e in the command line) always win
# then comes connection variables defined in inventory (ansible_ssh_user, etc)
# then comes "most everything else" (command line switches, vars in play, included vars, role vars, etc)
# then comes the rest of the variables defined in inventory
# then comes facts discovered about a system
# then "role defaults", which are the most "defaulty" and lose in priority to everything.


# Ports
#hostvars = global ansible vars, and ansible_nodename = current node.
# solr_host IPs referenced from:
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variables-discovered-from-systems-facts
solr_host: "0.0.0.0"
solr_port: 8983
solr_url: http://{{ solr_host }}:{{ solr_port }}/solr
# solr_jmx_enabled: 'true'
# solr_jmx_port: 1099

# Files & Paths
solr_install_dir: /users/dporte7/solr-8_0
solr_log_dir: /var/log/solr
solr_home: /users/dporte7//solr/server/solr
solr_data_dir: "/var/lib/"
solr_collections_config_tmp_dir: /tmp/collections


#booting solr vars
solr_service_manage: true
solr_service_name: solr
solr_service_state: started

# # Logs
# solr_log_root_level: WARN
# solr_log_file_size: 500MB
# solr_log_max_backup_index: 9
# solr_log_config_file: log4j2.xml
# solr_log_file_name: solr.log
# solr_log_slow_queries_file_name: solr_slow_requests.log

# # JVM
# solr_gc_tune: "-XX:NewRatio=3 \
# -XX:SurvivorRatio=4 \
# -XX:TargetSurvivorRatio=90 \
# -XX:MaxTenuringThreshold=8 \
# -XX:+UseConcMarkSweepGC \
# -XX:+UseParNewGC \
# -XX:ConcGCThreads=4 \
# -XX:ParallelGCThreads=4 \
# -XX:+CMSScavengeBeforeRemark \
# -XX:PretenureSizeThreshold=64m \
# -XX:+UseCMSInitiatingOccupancyOnly \
# -XX:CMSInitiatingOccupancyFraction=50 \
# -XX:CMSMaxAbortablePrecleanTime=6000 \
# -XX:+CMSParallelRemarkEnabled \
# -XX:+ParallelRefProcEnabled \
# -XX:+AggressiveOpts \
# -XX:+UseFastAccessorMethods \
# -XX:+UseTLAB"
# solr_stack_size: 256k
# solr_heap: 512m
#
# # Jetty
# solr_jetty_threads_min: 10
# solr_jetty_threads_max: 10000
# solr_jetty_threads_idle_timeout: 5000
# solr_jetty_threads_stop_timeout: 60000
# solr_jetty_secure_port: 8443
# solr_jetty_output_buffer_size: 32768
# solr_jetty_output_aggregation_size: 8192
# solr_jetty_request_header_size: 8192
# solr_jetty_response_header_size: 8192
# solr_jetty_send_server_version: 'false'
# solr_jetty_send_date_header: 'false'
# solr_jetty_header_cache_size: 512
# solr_jetty_delay_dispatch_until_content: 'false'
# solr_jetty_http_selectors: -1
# solr_jetty_http_acceptors: -1
#
# # Zookeeper
# solr_zookeeper_hosts: localhost:2181
# solr_zookeeper_hosts_solr_path: solr
# solr_zk_host: "{{ solr_zookeeper_hosts }}/{{ solr_zookeeper_hosts_solr_path }}"
# solr_zookeeper_client_path: "{{ solr_installation_dir }}/server/scripts/cloud-scripts"
# solr_zookeeper_client_timeout: 15000
#
# # Collections configuration
# solr_collections: {}
# solr_collections_template_path: "{{ playbook_dir }}/templates/collections/"
