---
# defaults file for upload_data
data_upload_dir: /users/dporte7
# collection name is passed in now
collection_name: "reviews_rf{{replicas}}_s{{shards}}_clustersize{{clustersize}}"
aws_dir_name: "{{ansible_subnet}}/reviews_rf{{replicas}}_s{{shards}}_clustersize{{clustersize}}"
solr_install_dir: /users/dporte7/solr-8_3
upload_data_file_path: /Users/dporter/projects/solrcloud/playbooks/roles/upload_data/files
nfs_root: /proj/uic-cs-edu-PG0/exp/solr8/datastore
solr_home: /users/dporte7/solr-8_3/solr/server/solr
tasks_dir: /Users/dporter/projects/solrcloud/playbooks/roles/upload_data/tasks
