# playbook for cloudconfig



- hosts: eightNode
  roles:
    - upload_data
  tags:
    - never
    - begin_exp

- hosts: singleNode
  tasks:
    - name: this task will run when aws_index is false
      include_tasks: roles/upload_data/tasks/aws_absent.yml
  tags:
    - never
    - begin_exp

- hosts: eightNode
  tasks:
    - name: update solr.xml
      copy:
        src: /Users/dporter/projects/solrcloud/playbooks/roles/upload_data/files/solr.xml
        dest: /users/dporte7/solr-8_3/solr/server/solr/
        force: yes
  tags:
    - begin_exp

- hosts: eightNode
  tasks:
    - name: run this at the end of each experiment AKA aws_exp_reset
      include_tasks:
        file: roles/upload_data/tasks/aws_reset.yml
  tags:
    - never
    - aws_exp_reset

- hosts: singleNode
  tasks:
    - name: update collection configs
      include_tasks:
        file: roles/upload_data/tasks/all_config.yml
  tags:
    - never
    - update_collection_configs
