# playbook for cloudconfig



- hosts: solrNodes
  roles:
    - upload_data
  tags:
    - never
    - begin_exp

- hosts: singleNode
  tasks:
    - name: this task will run when aws_index is false
      include_tasks: roles/upload_data/tasks/aws_absent.yml
  tags:
    - never
    - begin_exp

- hosts: solrNodes
  tasks:
    - name: run this at the end of each experiment AKA aws_exp_reset
      include_tasks:
        file: roles/upload_data/tasks/aws_reset.yml
  tags:
    - never
    - aws_exp_reset

- hosts: singleNode
  tasks:
    - name: update collection configs
      include_tasks:
        file: roles/upload_data/tasks/all_config.yml
  tags:
    - never
    - update_collection_configs

- hosts: solrNodes
  tasks:
    - name: delete aws index
      include_tasks:
        file: roles/upload_data/tasks/rm_aws_index.yml
  tags:
    - never
    - rm_index
